const names = [
  "abdel",
  "guthl",
  "sylve",
  "sam",
  "loaf",
  "odin-free",
  "cecco",
  "ybs",
  "starknet-intern",
  "eli",
  "uri",
  "jonasnelle",
  "braavos",
  "Argent",
  "Astraly",
  "Mintsquare",
  "Cartridge",
  "ZKX",
  "ZkLend",
  "Realms",
  "MES Protocol",
  "Maker",
  "Magnety",
  "JediSwap",
  "Dope wars",
  "Aspect",
  "Eykar",
  "Zohal",
  "ZigZag",
  "Yagi",
  "StarkBoard",
  "Phi",
  "Matchbox",
  "Influence",
  "Imperium",
  "Imperium-wars",
  "Hashstack",
  "Fuji Dao",
  "Fibrous",
  "Carbonable",
  "Briq",
  "Brine",
  "Alpha Road",
  "Onlydust",
  "Yagi",
  "xBank",
  "tradeflow",
  "starkswap",
  "starksheet",
  "starkdefi",
  "Starcombo",
  "Sithswap",
  "Serity",
  "Sandclock",
  "Nostra",
  "Myswap",
  "Frens Lands",
  "star",
  "Articium",
  "Apibara",
  "starkpiller",
];

const namesWithRightCharacter = names.map((name) =>
  name.replace(" ", "-").toLowerCase()
);

console.log("namesWithRightCharacter", namesWithRightCharacter);
