import "../styles/globals.css";
import type { AppProps } from "next/app";
import Navbar from "../components/navbar";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Starkbet.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/visuals/StarknetIdLogo.png" />
      </Head>{" "}
      <Navbar />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
